
import type { User, Listing } from './types';

// This is now a mock author, not the currently signed-in user.
export const mockAuthor: User = {
  id: 'user-1',
  name: 'Jane Doe',
  email: 'jane.doe@thechurch.org',
  churchName: 'Community Church',
};

export const mockUsers: User[] = [
  mockAuthor,
  { id: 'user-2', name: 'John Smith', email: 'john.s@thechurch.org', churchName: 'First Baptist' },
  { id: 'user-3', name: 'Sarah Lee', email: 'sarah.l@thechurch.org', churchName: 'Grace Fellowship' },
  { id: 'user-4', name: 'Mike Chen', email: 'mike.c@thechurch.org', churchName: 'New Life Assembly' },
  { id: 'user-5', name: 'Emily White', email: 'emily.w@thechurch.org', churchName: 'CityLight Church' },
  { id: 'user-6', name: 'David Green', email: 'david.g@thechurch.org', churchName: 'Oakhaven Community' },
  { id: 'user-7', name: 'Maria Rodriguez', email: 'maria.r@thechurch.org', churchName: 'El Camino' },
  { id: 'user-8', name: 'Tom Wilson', email: 'tom.w@thechurch.org', churchName: 'The Rock' },
  { id: 'user-9', name: 'Jessica Brown', email: 'jessica.b@thechurch.org', churchName: 'Riverwood Chapel' },
  { id: 'user-10', name: 'Chris Taylor', email: 'chris.t@thechurch.org', churchName: 'Metro Vineyard' },
];


export const mockListings: Listing[] = [
  {
    id: 'listing-1',
    title: 'Gently Used Stage Lights (Set of 4)',
    description:
      'We upgraded our stage lighting and have a set of 4 perfectly working LED stage lights. Great for a smaller venue or youth room. Comes with all necessary cables.',
    category: 'Give',
    subCategory: 'Gear',
    location: '90210',
    condition: 'Like New',
    contactPreference: 'Message',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1714618976010-a5b5c6dc1d32?q=80&w=4042&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    author: mockUsers[1],
    authorId: 'user-2',
    createdAt: '2024-05-20T14:30:00Z',
  },
  {
    id: 'listing-2',
    title: 'Kids Ministry VBS Curriculum (Unused)',
    description:
      'Complete "Space Explorers" VBS kit for 50 children. We bought this last year but ended up going a different direction. All materials are in original packaging.',
    category: 'Sell',
    subCategory: 'Curriculum',
    location: '60601',
    condition: 'New',
    contactPreference: 'Message',
    imageUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?q=80&w=4142&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    price: 150,
    author: mockUsers[2],
    authorId: 'user-3',
    createdAt: '2024-05-19T11:00:00Z',
  },
  {
    id: 'listing-3',
    title: 'Sermon Series Graphics Package',
    description:
      'Complete graphics package for a 4-week series on "Hope". Includes sermon slides (ProPresenter), social media templates (Canva), and bumper video. Happy to share our work!',
    category: 'Share',
    subCategory: 'Creative Assets',
    location: '30303',
    condition: 'New',
    contactPreference: 'Email',
    imageUrl: 'https://images.unsplash.com/photo-1501612780327-45045538702b?q=80&w=600&h=400&auto=format&fit=crop',
    author: mockUsers[0],
    authorId: 'user-1',
    createdAt: '2024-05-21T09:00:00Z',
  },
  {
    id: 'listing-4',
    title: 'Portable Sound System',
    description:
      'Yamaha StagePas 400i portable sound system. Includes two speakers, a mixer, and stands. Perfect for mobile church or outdoor events. Some cosmetic wear but works great.',
    category: 'Sell',
    subCategory: 'Gear',
    location: '75001',
    condition: 'Used',
    contactPreference: 'Message',
    imageUrl: 'https://images.unsplash.com/photo-1581335756312-5a2162520a0a?q=80&w=600&h=400&auto=format&fit=crop',
    price: 300,
    author: mockUsers[3],
    authorId: 'user-4',
    createdAt: '2024-05-18T16:45:00Z',
  },
  {
    id: 'listing-5',
    title: '12 Folding Chairs',
    description: 'We have 12 surplus folding chairs in good condition. Standard grey metal frame with plastic seat and back. Available for pickup anytime.',
    category: 'Give',
    subCategory: 'Gear',
    location: '10001',
    condition: 'Used',
    contactPreference: 'Message',
    imageUrl: 'https://images.unsplash.com/photo-1549497538-27c191c4a165?q=80&w=600&h=400&auto=format&fit=crop',
    author: mockUsers[4],
    authorId: 'user-5',
    createdAt: '2024-05-22T10:00:00Z',
  },
  {
    id: 'listing-6',
    title: 'Easter Production Costumes',
    description: 'A collection of costumes used for our Easter production. Includes shepherd, Roman soldier, and various villager outfits. Adult sizes.',
    category: 'Share',
    subCategory: 'Creative Assets',
    location: '94102',
    condition: 'Like New',
    contactPreference: 'Email',
    imageUrl: 'https://images.unsplash.com/photo-1599387229532-0a238a53e496?q=80&w=600&h=400&auto=format&fit=crop',
    author: mockUsers[5],
    authorId: 'user-6',
    createdAt: '2024-05-17T13:20:00Z',
  },
  {
    id: 'listing-7',
    title: 'Youth Group Summer Camp Guide',
    description: 'Full 8-week curriculum for a youth group summer program. Includes games, lessons, and small group materials. Theme is "Identity".',
    category: 'Sell',
    subCategory: 'Curriculum',
    location: '33101',
    condition: 'New',
    contactPreference: 'Message',
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=600&h=400&auto=format&fit=crop',
    price: 50,
    author: mockUsers[6],
    authorId: 'user-7',
    createdAt: '2024-05-21T18:00:00Z',
  },
  {
    id: 'listing-8',
    title: 'Behringer X32 Digital Mixer',
    description: 'Excellent condition Behringer X32 digital mixer. We are upgrading our soundboard and no longer need this one. Fully functional, includes road case.',
    category: 'Sell',
    subCategory: 'Gear',
    location: '77002',
    condition: 'Like New',
    contactPreference: 'Message',
    imageUrl: 'https://images.unsplash.com/photo-1606563424369-269382903426?q=80&w=600&h=400&auto=format&fit=crop',
    price: 1200,
    author: mockUsers[7],
    authorId: 'user-8',
    createdAt: '2024-05-16T09:30:00Z',
  },
  {
    id: 'listing-9',
    title: 'Office Desks (x3)',
    description: 'Three sturdy office desks available for free. Light wood finish. Dimensions are 60"x30". Must be picked up.',
    category: 'Give',
    subCategory: 'Gear',
    location: '80202',
    condition: 'Used',
    contactPreference: 'Message',
    imageUrl: 'https://images.unsplash.com/photo-1555627772-46ab4a84553e?q=80&w=600&h=400&auto=format&fit=crop',
    author: mockUsers[8],
    authorId: 'user-9',
    createdAt: '2024-05-22T11:45:00Z',
  },
  {
    id: 'listing-10',
    title: 'Marriage Counseling Premarital Books',
    description: 'A box of 20 "Saving Your Marriage Before It Starts" books by Les and Leslie Parrott. We have surplus from our premarital counseling program.',
    category: 'Give',
    subCategory: 'Curriculum',
    location: '20001',
    condition: 'New',
    contactPreference: 'Email',
    imageUrl: 'https://images.unsplash.com/photo-1593340087093-951dec584c35?q=80&w=600&h=400&auto=format&fit=crop',
    author: mockUsers[9],
    authorId: 'user-10',
    createdAt: '2024-05-15T15:00:00Z',
  },
  {
    id: 'listing-11',
    title: 'Projector for Sanctuary',
    description: 'We have a spare Epson PowerLite projector that is bright enough for a small to medium-sized sanctuary. 5000 lumens, HDMI input. Available to borrow for special events.',
    category: 'Share',
    subCategory: 'Gear',
    location: '98101',
    condition: 'Used',
    contactPreference: 'Message',
    imageUrl: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?q=80&w=600&h=400&auto=format&fit=crop',
    author: mockUsers[0],
    authorId: 'user-1',
    createdAt: '2024-05-20T12:00:00Z',
  },
  {
    id: 'listing-12',
    title: 'Stock Photos for Church Website',
    description: 'A collection of 50 high-resolution stock photos we commissioned for our church. People-focused, diverse, and modern. We are happy to share them with another church.',
    category: 'Share',
    subCategory: 'Creative Assets',
    location: '02108',
    condition: 'New',
    contactPreference: 'Email',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=600&h=400&auto=format&fit=crop',
    author: mockUsers[2],
    authorId: 'user-3',
    createdAt: '2024-05-18T20:00:00Z',
  },
];

    